name: Waka Readme

on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LOC_CHART: False
          SHOW_UPDATED_DATE: False
          COMMIT_MESSAGE: "Updated readme statistics"
          COMMIT_BY_ME: True
          LOCALE: "en"
          SHOW_PROFILE_VIEWS: False
          SHOW_LINES_OF_CODE: True
          SHOW_TIMEZONE: False
